### ISSUE TITLE
Porting to Blazor or/and WebAssembly

### ISSUE THREAD

**Issue by YordanYanakiev** [Mapsui/backlog#9]
Hello.
I am just excited with Blazor and WebAssembly, and just as an idea - it could be cool to have it the MapsUI as Web port written in C# for Blazor and/or eventually as WebAssembly.
( Skyasharp is having port now to Blazor )
Seems like Microsoft have some great plans for Blazor as complete crossplatform framework in C# (Web/Desktop/Mobiles) so.. maybe it would be cool to have the awesome maps in there as well. :)

**Comment by pauldendulk** [comment]
In 4.0.0 Blazor was added as one of the supported platforms.

**Comment by YordanYanakiev** [comment]
Sorry for bothering, but is it Blazor WebAssembly or Blazor Server  ?

**Comment by pauldendulk** [comment]
ah, you are even responding to this ancient issue :). It is Blazor WebAssembly, and that is the only option that really makes sense. I have seen Leaflet used in Blazor Server mode and this means streaming images rendered on the server to the client. It is horribly slow. A problem in .NET 7 is that you have to choose upfront if yoru project is WebAssembly or Server.  In .NET8 it becomes possible to specify for each part if you want WebAssembly or Server rendering. So, I think these removes all barriers to use Mapsui in Blazor. Did not test that yet.
